name: End-to-end Tests
on: push
jobs:
  tests-linux:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Cypress Tests 🧪
        uses: cypress-io/github-action@v6
      - name: Save screenshots in case of failures
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-linux
          path: cypress/screenshots
          if-no-files-found: ignore

  tests-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Cypress Tests 🧪
        uses: cypress-io/github-action@v6
      - name: Save screenshots in case of failures
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots-windows
          path: cypress/screenshots
          if-no-files-found: ignore
